### PR TITLE
Update README.rdoc

### PR DESCRIPTION
**Pull request by yaboyanees**
Added the example walkthrough section to replace the example section. May be easier for people to follow and adapt to their existing applications.

### CODE REVIEW

**Comment by collegeimprovements** [comment]
thank you for this :)
@yaboyanees what is calendar in the _show.html.erb ? where is it defined ?

**Comment by yaboyanees** [comment]
@collegeimprovements, my apologies. I'll update the example to remove this and start date. At the time, I was using a calendar builder to put who was working at a given time and date.

**Comment by yaboyanees** [comment]
It was the simple_calendar gem found here: https://github.com/excid3/simple_calendar

**Comment by collegeimprovements** [comment]
ah...ok. I found your example useful. Thank you  for your efforts :)

**Comment by yaboyanees** [comment]
@collegeimprovements, glad it helped you.

**Pull request closed without merging**
